"""
Django settings for donworry project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

###################################
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
API_KEYS = {
    'FINLIFE_API_KEY': os.getenv('FINLIFE_API_KEY'),
    'KIS_MOCK_APP_KEY': os.getenv('KIS_MOCK_APP_KEY'),
    'KIS_MOCK_APP_SECRET': os.getenv('KIS_MOCK_APP_SECRET'),
}
###################################

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9l^_s5ov=&u48r5#lca#v(sih2jwykfkw659(qqpp(koy4#y!t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#############################################################
ALLOWED_HOSTS = ['15.165.238.176', '*', '127.0.0.1']
#############################################################
AUTH_USER_MODEL = 'accounts.User'

#############################################################
FINLIFE_API_KEY = os.getenv('FINLIFE_API_KEY')
#############################################################

# Application definition

INSTALLED_APPS = [
    ########################################
    # 실시간 데이터를 보여주기 위한 app
    'daphne',
    'channels',
    #######################################
    'rest_framework',
    'accounts',
    'products',
    'survey',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'donworry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS를 Vue함수의 dist로 수정
        'DIRS': [os.path.join(BASE_DIR, '../donworry-frontend/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'donworry.wsgi.application'

# ASGI도 같이 설정
ASGI_APPLICATION = 'donworry.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 정적 파일(JS, CSS) 경로 추가
STATIC_URL = 'assets/' # Vue 빌드 결과물을 저장하는 공간
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '../donworry-frontend/dist/assets'),
]

##############################################################
# 채널 레이어 설정 (Redis 필요)
# 우선 로컬에서 Docker로 Redis를 띄웠다고 가정합니다. (port: 6379)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
################################################################