# Generated by Django 5.2.14 on 2026-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='deposit', max_length=20),
        ),
    ]
