# Generated by Django 5.2.14 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='join_member',
            field=models.TextField(null=True),
        ),
    ]
